### ISSUE TITLE
GPT4Free integration possibility

### ISSUE THREAD

**Issue by kirill670** [MrMatch246/rAIversing#14]
Is it possible to integrate gpt4free instead of API Key? Thanks in advance)

**Comment by MrMatch246** [comment]
You can fork this repository,
add a class implementing this [Interface](https://github.com/MrMatch246/rAIversing/blob/main/modules/rAIversing/AI_modules/__init__.py)

and then call it [here](https://github.com/MrMatch246/rAIversing/blob/7db1cf2a7595f5b5864ec51d890cd280757ac2a7/modules/rAIversing.py#L158)
