### ISSUE TITLE
Chatbot is not defined [workaround in comments]

### ISSUE THREAD

**Issue by kirill670** [MrMatch246/rAIversing#3]
![Снимок экрана 2023-06-14 005301](https://github.com/MrMatch246/rAIversing/assets/51964569/a599cfa5-2128-40c2-a7da-d185323a69b4)

**Comment by MrMatch246** [comment]
Yeah revChatGPT isnt updated to support gpt-3.5-turbo-16k yet so i manually did that.
clone it to `rAIversing/modules/external/ChatGPT` and add the following lines to chatGPT.py :
```
from external.ChatGPT.src.revChatGPT.V3 import * 
from external.ChatGPT.src.revChatGPT.typings import *
```
and the following after line 131 in  `rAIversing/modules/external/ChatGPT/src/revChatGPT/V3.py`  :
```
"gpt-3.5-turbo-16k",
```

resulting in this :
<img width="442" alt="image" src="https://github.com/MrMatch246/rAIversing/assets/50702646/4faa6514-4a2f-43b1-b4ff-530e918bc12f">

**Comment by MrMatch246** [comment]
Fixed now
