### ISSUE TITLE
Another error

### ISSUE THREAD

**Issue by kirill670** [MrMatch246/rAIversing#6]
![image](https://github.com/MrMatch246/rAIversing/assets/51964569/aa68176c-2ee1-4678-9be4-fa1e34460675)

**Comment by MrMatch246** [comment]
Try to run it with debug=true [Here](https://github.com/MrMatch246/rAIversing/blob/1b11cc6c109c51c0cd5bac723a70d8f92e01e36f/modules/rAIversing.py#L69)

**Comment by MrMatch246** [comment]
Also Win PS is currently not tested at all. Get WSL
