### ISSUE TITLE
Error on WSL

### ISSUE THREAD

**Issue by kirill670** [MrMatch246/rAIversing#9]
![image](https://github.com/MrMatch246/rAIversing/assets/51964569/792d3808-b8b7-46d1-91e2-33e4eebd7297)

**Comment by MrMatch246** [comment]
Again : Try to run it with debug=true added in this here [click me](https://github.com/MrMatch246/rAIversing/blob/1b11cc6c109c51c0cd5bac723a70d8f92e01e36f/modules/rAIversing.py#L69)

**Comment by kirill670** [comment]
![image](https://github.com/MrMatch246/rAIversing/assets/51964569/0313ae48-23e6-4ed1-b997-f893c965a5f5)

**Comment by MrMatch246** [comment]
Well it looks like you dont have the right permissions set for the analyzeHeadless binary
`drwxr-xr-x 9 user user 4.0K Nov 15  2022 ghidra_10.2.2_PUBLIC`
and
`-rwxr-xr-x 1 user user 1.7K Nov 15  2022 analyzeHeadless`
if the x is missing then run `chmod +x analyzeHeadless`

**Comment by kirill670** [comment]
![image](https://github.com/MrMatch246/rAIversing/assets/51964569/4b1046e1-91c4-42a8-9a54-8bb0865863b8)
